import type { INodeProperties } from 'n8n-workflow';

const showOnlyForSendAudio = {
	resource: ['message'],
	operation: ['sendAudio'],
};

export const sendAudioDescription: INodeProperties[] = [
	{
		displayName: 'Phone',
		name: 'phone',
		type: 'string',
		required: true,
		default: '',
		description: 'Número WhatsApp em formato internacional, ex.: 5511999999999',
		displayOptions: { show: showOnlyForSendAudio },
	},
	{
		displayName: 'Audio (Base64)',
		name: 'audio',
		type: 'string',
		required: true,
		typeOptions: { rows: 4 },
		default: '',
		description: 'Conteúdo base64 incluindo prefixo ex: data:audio/ogg;base64,',
		displayOptions: { show: showOnlyForSendAudio },
	},
	{
		displayName: 'PTT',
		name: 'ptt',
		type: 'boolean',
		required: true,
		default: true,
		description: 'Whether the message should be marked as PTT (push-to-talk)',
		displayOptions: { show: showOnlyForSendAudio },
	},
	{
		displayName: 'Mime Type',
		name: 'mimeType',
		type: 'string',
		required: true,
		default: 'audio/ogg; codecs=opus',
		description: 'Tipo MIME do áudio enviado',
		displayOptions: { show: showOnlyForSendAudio },
	},
	{
		displayName: 'Seconds',
		name: 'seconds',
		type: 'number',
		required: true,
		default: 0,
		description: 'Duração do áudio em segundos',
		displayOptions: { show: showOnlyForSendAudio },
	},
	{
		displayName: 'Waveform',
		name: 'waveform',
		type: 'string',
		required: true,
		typeOptions: { rows: 3 },
		default: '[0,0,0,12,20,20,22,10,5,0,0,0]',
		description: 'Array JSON com os níveis do waveform, ex.: [0,0,12,...]',
		displayOptions: { show: showOnlyForSendAudio },
	},
	{
		displayName: 'Additional Options',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add option',
		default: {},
		displayOptions: { show: showOnlyForSendAudio },
		options: [
			{
				displayName: 'Context Is Forwarded',
				name: 'isForwarded',
				type: 'boolean',
				default: false,
				description: 'Whether the message is forwarded',
			},
			{
				displayName: 'Context Mentioned JIDs',
				name: 'mentionedJid',
				type: 'string',
				typeOptions: { rows: 3 },
				default: '',
				description: 'Liste os JIDs separados por vírgula ou quebra de linha',
			},
			{
				displayName: 'Context Participant',
				name: 'participant',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Context Stanza ID',
				name: 'stanzaId',
				type: 'string',
				default: '',
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'string',
				default: '',
				description: 'Identificador opcional para controle do cliente',
			},
		],
	},
];
